version: '3.7'
services:
  pokemon:
    image: ultrajcr/pokemon-react:latest
    container_name: pokemon
    hostname: pokemon
    ports:
      - 3033:3000
    networks:
      - network
networks:
  network:
    driver: bridge