version: '3.7'
services:
  pokemon:
    image: mon-site:latest
    container_name: pokemon
    hostname: pokemon
    ports:
      - 3001:3000
    networks:
      - network
networks:
  network:
    driver: bridge